[package]
name = "password-tool"
version = "0.1.0"
authors = ["justine brun <just.brun@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.27.0"